version: '3.8'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - backend

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.8.0
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #   ports:
  #     - '5601:5601'
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - backend

networks:
  backend:
    driver: bridge
