version: '3.8'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 300m
        reservations:
          memory: 200m

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 500m
        reservations:
          memory: 400m

  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: app
    ports:
      - '8000:8000'
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 100m

networks:
  backend:
    driver: bridge
